---
title: "STAT 184 Final Project"
author: "Zinuo Jia, Alexander Kim"
date: "12/17/2019"
output: html_notebook
---


### Front Matter

```{r}
# clean up the RStudio environment 
rm(list = ls())
# load all packages needed
library(mosaic)
library(DataComputing)
library(tidyverse)
library(lubridate)
library(leaflet)
library(rvest)
library(readr)
```

Importing Data
```{r}
#Source data "vgsales.csv" downloaded from "Kaggle.com/dataset"
#vgsales.csv already uploaded in the repo
vgsales <- read_csv("vgsales.csv")
#load source data "vgconsole" from "https://en.wikipedia.org/wiki/List_of_best-selling_game_consoles" 
page <- "https://en.wikipedia.org/wiki/List_of_best-selling_game_consoles" 
tableList <- page %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
vgconsole<-tableList[[1]]
vgconsole$Ref. <- NULL #took out the Ref. column that has no value
head(vgconsole)
head(vgsales)
```

### Introduction  
Seeing which platform had the greatest sale and within each platform what was the greatest sold game 
```{r}
vgsales %>%
  group_by(Platform) %>%
  filter(rank(desc(Global_Sales))==1)
ggplot(data=vgsales,aes(x=reorder(Platform,-Global_Sales),y=Global_Sales ))+geom_bar(stat='identity',position='stack', width=.9) + theme(axis.text.x=element_text(angle=60,hjust=1)) 
```


Most Sold Game
```{r}
sold <- vgsales %>%
  group_by(Platform) %>%
  filter(rank(desc(Global_Sales))==1)
  
ggplot(data=sold, aes(x=reorder(Name,-Global_Sales),y=Global_Sales )) + geom_bar(stat='identity',position='stack', width=.9) + theme(axis.text.x=element_text(angle=60,hjust=1)) + xlab("Game Title") + ylab("Global Sales")
```

